# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      PYTHON_VERSION: '3.10'
  maxParallel: 3

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install prerequisites'

- script: |
    python manage.py test
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/reports/test-results.xml'
    testRunTitle: 'Django Tests'
  condition: succeededOrFailed()
  
- script: |
        mkdir -p $(Build.ArtifactStagingDirectory)/build_output
        echo "Build artifacts go here" > $(Build.ArtifactStagingDirectory)/build_output/output.txt
  displayName: 'Prepare Build Artifacts'


- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'my-artifact'  # Name of the artifact
    publishLocation: 'Container'  # Store the artifact in the Azure Pipelines container
    pathToPublish: '$(Build.ArtifactStagingDirectory)/build_output'  # Path to the folder containing files to publish