# Python Django
# Test a Django project on multiple versions of Python.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/pythond

trigger:
- main

pool:
    name: Default       

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'use python 3.11'

# Install Microsoft Visual C++ Build Tools (required for compiling mysqlclient)
- powershell: |
    Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_BuildTools.exe -OutFile vs_BuildTools.exe
    Start-Process vs_BuildTools.exe -ArgumentList '--quiet', '--wait', '--norestart', '--add', 'Microsoft.VisualStudio.Workload.VCTools' -NoNewWindow -Wait
  displayName: 'Install Microsoft C++ Build Tools'

# Download MySQL Connector C and add to path
- powershell: |
    Invoke-WebRequest -Uri https://dev.mysql.com/get/Downloads/Connector-C/mysql-connector-c-6.1.11-win32.msi -OutFile mysql-connector.msi
    Start-Process msiexec.exe -ArgumentList '/i', 'mysql-connector.msi', '/quiet', '/norestart' -NoNewWindow -Wait
    $env:path += ';C:\Program Files\MySQL\MySQL Connector C 6.1\lib'
  displayName: 'Install MySQL Connector C'



- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install prerequisites'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
     pip install pytest pytest-azurepipelines
     pytest
  displayName: 'pytest'
